default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: beer_league_development

test:
  <<: *default
  database: beer_league_test

production:
  <<: *default
  socket: /var/run/mysqld/mysqld.sock
  database: rails
  username: root
  password: <%= ENV['BEER_LEAGUE_DATABASE_PASSWORD'] %>
